Build for antiX-15

diff --git a/bin/persist-makefs b/bin/persist-makefs
--- a/bin/persist-makefs
+++ b/bin/persist-makefs
@@ -9,6 +9,12 @@
 source /usr/local/lib/antiX/antiX-common.sh  "$@"
 
 SAFETY_MARGIN=10
+  rootfs_SIZE_PARAM="min_size=250 mid_size=100 max_size=4000 factor=50"
+  homefs_SIZE_PARAM="min_size=250 mid_size=100 max_size=3000 factor=25"
+
+    VFAT_MKFS_SIZES="250 375 500 750 1000 1500 2000 2500 3000 4000"
+         MKFS_SIZES="250 375 500 750 1000 1500 2000 2500 3000 4000 5000 6000"
+   MKFS_FREE_MARGIN=20
 
 # Files listed on the main screen
 ACTIVE_FILES="rootfs rootfs.bak homefs homefs.new homefs.old rootfs.old linuxfs.old"
@@ -19,7 +25,8 @@ OLDEN_FILES="rootfs.tmp rootfs.bak homefs.old rootfs.old linuxfs.old"
 # Files we will only delete after e2fsck fails
 LIVE_FILES="rootfs homefs homefs.new"
 
-CONF_FILE=/live/config/linuxrc.out
+CONF_FILE=$LIVE_DIR/config/initrd.out
+[ -r $CONF_FILE ] || CONF_FILE=$LIVE_DIR/config/linuxrc.out
 
 TITLE="$(gt "antiX Create or Resize Persistence")"
 BLURB="$(gt "Create or resize the files need for root and/or home persistence.")"
@@ -76,30 +83,44 @@ d,dev,device|o|DEV
    r,rootfs||ROOTFS
 "
 
-main() {
+prep_main() {
     add_options "$OPTIONS"
     read_options "$@"
 
     SYS_TYPE="LiveCD/USB/HD"
-    conf_file=$CONF_DIR/linuxrc.out
-    read_conf $conf_file || read_conf_error rootfs $conf_file
+    read_conf $CONF_FILE || read_conf_error rootfs $CONF_FILE
 
     show_cli_title
     need_root
     start_logging
     trap clean_up EXIT
     create_lock
+}
 
+main() {
     # return after errors in mount_if_needed()
     nonfatal_mount_errors
 
     P_PATH=$PERSIST_PATH
-    [ "$P_PATH" ] || P_PATH=$SQFILE_PATH
-    [ "$P_PATH" ] || P_PATH=$DISTRO
+    : ${P_PATH:=$SQFILE_PATH}
+    : ${P_PATH:=$DISTRO}
 
-    DEV=$PERSIST_DEV
-    [ "$DEV" ] || DEV=$BOOT_DEV
-    [ "$OPT_DEV" ] && DEV=$OPT_DEV
+    # Let command line override
+    DEV=$OPT_DEV
+
+    # First try to find the persist device (if any)
+    while [ -z "$DEV" -a -n "$PERSIST_UUID" ]; do
+        DEV=$(blkid -U "$PERSIST_UUID")
+        [ "$DEV" ] && break
+        no_yes_box \
+            "$(pfgt "The persistence device with UUID %s was not found" "[n]$PERSIST_UUID[/]")" \
+            "$(pfgt "Please plug in the persistence device if you want to use it.")" \
+            ""                                                                      \
+            "$(gt "Do you want to try again?")" || break
+    done
+
+    # If there is no persist device then use the boot device
+    [ -z "$DEV" -a -n "$BOOT_UUID" ] && ${DEV:=$(blkid -U $BOOT_UUID)}
 
     if ! [ -b "$DEV" ]; then
         okay_box  "$TITLE" "" \
@@ -129,7 +150,7 @@ main() {
 
         gather_device_info
         vmsg "Make rootfs.new"
-        make_filefs rootfs.new "$(gt "Create rootfs.new (for remastering)")" "" "$MAX_SIZE"
+        make_filefs rootfs.new "$(gt "Create rootfs.new (for remastering)")"
         exit
 
     elif [ "$SET_EXPLORE" ]; then
@@ -138,6 +159,8 @@ main() {
         explore_menu
         exit
     fi
+
+    LIVE_FS_TYPE=$(df -T $DEV | awk '{print $2}')
 
     while true; do
 
@@ -192,14 +215,14 @@ main() {
             "${DEVICE_TEXT[@]}"                  \
             "${FILE_TEXT[@]}"  ""
 
-        case "$UI_RESULT" in
+        case $UI_RESULT in
 
-            "$MAKE_ROOTFS")
+            $MAKE_ROOTFS)
                 vmsg "Make rootfs"
-                make_filefs rootfs "$(gt "Create Root")" "" "$MAX_SIZE"
+                make_filefs rootfs "$(gt "Create Root persistence")"
                 ;;
 
-            "$RESIZE_ROOTFS")
+            $RESIZE_ROOTFS)
                 rootfs="$FULL_PATH/rootfs"
                 if [ "$(get_mountpoint $rootfs)" ]; then
                     okay_box -c "[e]Warning[/]" "" \
@@ -208,58 +231,56 @@ main() {
                     continue
                 fi
                 vmsg "Resize rootfs"
-                make_filefs rootfs.tmp "$(gt "Resize Root")" "${USED_SPACE[rootfs]}" "$MAX_SIZE" \
-                    || continue
+                make_filefs rootfs.tmp "$(gt "Resize Root persistence")" || continue
 
-                if ! [ "$MADE_FS" = "rootfs.tmp" ]; then
-                    noisy_yes_no_box "$TITLE" "" \
-                        "$(gt "The resize rootfs has failed.")" \
-                        "$(pfgt "Shall I delete the %s file?" "[f]rootfs.tmp[/]")" \
-                        && rm -f $rootfs.tmp
-                    continue
-                fi
+                # if ! [ "$MADE_FS" = "rootfs.tmp" ]; then
+                #     noisy_yes_no_box "$TITLE" "" \
+                #         "$(gt "The resize rootfs has failed.")" \
+                #         "$(pfgt "Shall I delete the %s file?" "[f]rootfs.tmp[/]")" \
+                #         && rm -f $rootfs.tmp
+                #     continue
+                # fi
                 copy_filefs "$rootfs" "$rootfs.tmp" "${USED_SPACE[rootfs]}" || continue
                 mv -f $rootfs $rootfs.bak
                 mv -f $rootfs.tmp $rootfs
                 ;;
 
-            "$MAKE_ROOTFS_NEW")
+            $MAKE_ROOTFS_NEW)
                 vmsg "Make rootfs.new"
-                make_filefs rootfs.new "$(gt "Create rootfs.new (for remastering)")" "" "$MAX_SIZE"
+                make_filefs rootfs.new "$(gt "Create %s (for remastering)" rootfs.new)"
                 ;;
 
-            "$MAKE_HOMEFS")
+            $MAKE_HOMEFS)
                 vmsg "Make homefs"
-                make_filefs "homefs" "$(gt "Create Home")" "" "$SAFE_AVAIL" "$(gt "Create Home")"
+                make_filefs "homefs" "$(gt "Create Home persistence")"
                 ;;
 
-            "$RESIZE_HOMEFS")
+            $RESIZE_HOMEFS)
                 vmsg "Resize homefs"
                 homefs="$FULL_PATH/homefs"
-                make_filefs "homefs.new" "$(gt "Resize Home")" "" "$SAFE_AVAIL" "$(gt "Resize Home")" \
-                    || continue
+                make_filefs "homefs.new" "$(gt "Resize Home persistence")" || continue
 
                 copy_filefs "$homefs" "$homefs.new" "${USED_SPACE[homefs]}"
                 ;;
 
-            "$CHANGE_DEV")
+            $CHANGE_DEV)
                 vmsg "Change device"
                 change_device
                 ;;
 
-            "$CHANGE_PATH")
+            $CHANGE_PATH)
                 vmsg "Change path"
                 change_path
                 ;;
 
-            "$EXPLORE_MENU")
+            $EXPLORE_MENU)
                 vmsg "Explore menu"
                 explore_menu
                 ;;
-            "$FIX_CHOICE")
+            $FIX_CHOICE)
                 fix_files_menu
                 ;;
-            "$QUIT")
+            $QUIT)
                 #exit
                 noisy_yes_no_box "$TITLE" "$(gt "Really Quit?")" && exit
                 ;;
@@ -268,11 +289,25 @@ main() {
     done
 }
 
-# push_text() {
-#     for t in "$@"; do
-#         MAIN_TEXT[${#MAIN_TEXT[*]}]="$t"
-#     done
-# }
+makefs() {
+    local file=$1  type=$2  size=$3
+    mkdir -p $(dirname $file)                                                    || return 1
+    time_cmd_quiet dd if=/dev/zero of=$file bs=1M count=0 seek=$size             || return 2
+    time_cmd_quiet mkfs.$type -F $file                                           || return 3
+}
+
+default_makefs_size() {
+    local avail=$1  size=$3  params
+    eval params=\$$2
+    eval local $params
+    [ "$avail" -lt $mid_size ] && factor=1
+    [ "$size" ] || size=$((mid_size + factor * ( avail - mid_size ) / 100))
+    [ $size -gt $max_size ] && size=$max_size
+    [ $size -gt $avail    ] && size=$avail
+    [ $size -lt $min_size ] && return 1
+    echo $size
+    return 0
+}
 
 select_ftype() {
     local choice ftype
@@ -281,43 +316,59 @@ select_ftype() {
     done
     combo_box "$(gt "File System Type")" "$choice" "" ""
     FTYPE="$(echo $UI_RESULT | cut -d: -f1)"
-
 }
 
 make_filefs() {
-    local file=$1  ptype=$2  min_size=$3  max_size=$4
-
+    local file=$1  ptype=$2
+    local min_size=250 max_size=$MAX_SIZE
     local full="$FULL_PATH/$file"
-    vmsg "make_filefs(\"$1\", \"$2\", \"$3\", \"$4\")"
     if [ -f "$full" ]; then
         yes_no_box "$TITLE" ""                                       \
             "$(pfgt "The file %s already exists" "[f]$file[/]")" ""  \
-            "${INFO_HASH[$file]}" ""                                 \
             "$(gt "Do you want to over-write it?")" ""               \
-            || return
+            || return 0
     fi
 
-    local text=(
-        "$(gt "Please select for the new partition")"
-        ""
-        "$(pfgt "For %s persistence" "[b]$ptype[/]")"
-    )
-    if ! select_size -min "$min_size" -Max "$max_size" "$msg"; then
-        warn_box "$TITLE" "" \
-            "$(pfgt "Not enough space on device to %s" "$ptype")" ""
-
+    local text="$ptype\n\n$(gt "Please select size of the new file system")"
+    if ! select_size -min "$min_size" -Max "$max_size" "" "$text"; then
+        warn_box "$TITLE" "" "$(pfgt "Not enough space on device")" ""
         return
     fi
     local size=$UI_RESULT
 
     #select_ftype
     FTYPE=ext4
-    vmsg "FTYPE=$FTYPE"
+    vmsg "filesystem type: $FTYPE"
+    local last_line
+
+    case $DEV_FS in
+        vfat) last_line=$(pfgt "Warning: this can take several minutes per Gig on a %s file system" "[b]$DEV_FS[/b]") ;;
+           *) last_line=$(gt "Please wait") ;;
+    esac
 
     make_path_if_needed "$DEV_MP" "$P_PATH"
 
-    if ! _make_filefs "$full" "$size" "$FTYPE"  "$opts"; then
-        warn_box "" "$(pfgt "Was unable to to create file %s" "[f]$file[/]")"
+    bg_info_box -o "$PULSATE"                                 \
+        ""                                                    \
+        "$(pfgt "Creating file %s" [f]$file[/])"              \
+        "$(pfgt "Size: %s Meg. Filesystem: %s" $size $FTYPE)" \
+        ""                                                    \
+        "$last_line"                                          \
+        ""
+
+    makefs "$full" $FTYPE $size;
+    local ret=$?
+
+    kill_bg_info_box
+    case $ret in
+        0) ;;
+        1) warn_box "" "$(pfgt "Was unable to create directory for file %s"         "[f]$file[/]")"  ;;
+        2) warn_box "" "$(pfgt "Was unable to create file %s"                       "[f]$file[/]")"  ;;
+        3) warn_box "" "$(pfgt "Was unable to make %s filesystem on file %s" $FTYPE "[f]$file[/]")"  ;;
+        *) warn_box "" "$(pfgt "Unknown error creating file %s"                     "[f]$file[/]")"  ;;
+    esac
+
+    if [ $ret -ne 0 ]; then
         rm -f $full
         return 2
     fi
@@ -332,7 +383,7 @@ make_filefs() {
 
     case $ret in
         0) okay_box "$TITLE" "" "$(pfgt "Success! File %s was created." "[f]$file[/]")" ;;
-    [123]) okay_box "$TITLE" "" "$(pfgt "Success! File %s was created and it's filesystem was fixed." "[f]$file[/]")" ;;
+    [123]) okay_box "$TITLE" "" "$(pfgt "Success! File %s was created and its filesystem was fixed." "[f]$file[/]")" ;;
         *) warn_box "" "$(pfgt "The filesystem on %s is broken and wasn't fixed" "[f]$file[/]")"
            rm -f $full
            return 4
@@ -406,7 +457,7 @@ change_device() {
 
         DEV=$UI_RESULT
 
-        mount_device $DEV
+        mount_device $DEV  # Assigns to $DEV_MP
 
         vmsg "Device: [n]$DEV[/],   Mountpoint: [f]$DEV_MP[/]"
 
@@ -437,7 +488,7 @@ change_path() {
     choice="$choice!$custom"
 
     combo_box "Path" "$choice" "$TITLE" "" \
-        "$(gt "Please choice an new persistence directory")" "" \
+        "$(gt "Please choose a new persistence directory")" "" \
         "$(pfgt "The current choice is %s" "[f]$P_PATH[/]")" ""
 
     if [ "$UI_RESULT" != "$custom" ]; then
@@ -701,6 +752,8 @@ unmount_device() {
 gather_device_info() {
     FULL_PATH="$DEV_MP/$P_PATH"
 
+    DEV_FS=$(df -T $DEV | tail -n1 | awk '{print $2'})
+
     FS_TOTAL=$(all_space  $DEV_MP)
     FS_AVAIL=$(free_space $DEV_MP)
     SAFE_AVAIL=$(( $FS_AVAIL - $SAFETY_MARGIN ))
@@ -709,6 +762,8 @@ gather_device_info() {
     SAFE_RAM=$(($TOTAL_RAM + $SAFETY_MARGIN))
 
     MAX_SIZE=$(min_of $SAFE_RAM $SAFE_AVAIL)
+
+    [ "$DEV_FS" = vfat -a $MAX_SIZE -gt 4095 ] && MAX_SIZE=4095
 
     DEVICE_TEXT=(                                                    \
         "[fixed]"                                                    \
@@ -747,4 +802,5 @@ gather_file_info() {
 
 }
 
-main "$@"
+prep_main "$@"
+main
